[addressbooks]
[[icloud]]
path = ~/.local/share/vdirsyncer/icloud_contacts/card/

[general]
debug = false
default_action = list
editor = nvim
merge_editor = nvim

[contact table]
display = first_name
group_by_addressbook = false
reverse = false
show_nicknames = false
show_uids = false
sort = last_name
localize_dates = true

[vcard]
preferred_version = 3.0
search_in_source_files = false
skip_unparsable = true
