# [accounts.gmail]
# default = true
# email = "daichao@gmail.com"
# display-name = "Chao Dai"
# downloads-dir = "/Users/chao/Downloads"
# backend.type = "imap"
# backend.host = "imap.gmail.com"
# backend.port = 993
# backend.login = "daichao@gmail.com"
# backend.encryption.type = "tls"
# backend.auth.type = "password"
# backend.auth.command = "security find-generic-password -s 'himalaya-gmail-imap' -a 'daichao@gmail.com' -w"
# message.send.backend.type = "smtp"
# message.send.backend.host = "smtp.gmail.com"
# message.send.backend.port = 465
# message.send.backend.login = "daichao@gmail.com"
# message.send.backend.encryption.type = "tls"
# message.send.backend.auth.type = "password"
# message.send.backend.auth.command = "security find-generic-password -a 'daichao@gmail.com' -s 'himalaya-gmail-imap' -w"
